; Bank the 8086 Edition
; authors: Parsa KamaliPour 97149081, Hosein Ahmadi 97149003

.MODEL SMALL

.DATA

    INTRO_MSG DB 'Bank The 8086 Edition$'

    CREATE_MSG DB 'CREATE ACCOUNT$'

    DEPO_MSG DB 'DEPOSIT MONEY$'

    WITHDRAW_MSG DB 'WITHDRAW MONEY$'

    ACC_INFO_MSG DB 'ACCOUNT INFORMATION$'

    CHANGE_ACC_INFO_MSG DB 'CHANGE YOUR ACCOUNT INFORMATION$'

    QUESTION_MSG DB 'Choose your next option: $'

    INPUT DB ?

    ACC_NAME DB 50 DUP('$')

    ACC_PASSWORD DB 50 DUP('$')

    PASSWORD_SIZE DW 0

    ACC_BALANCE DW 0

    ; CREATE ACCOUNT SECTION

    SEC1_ENTER_MSG DB 'ENTER YOUR NAME: $'
    SEC1_PASS_MSG DB 'ENTER YOUR PASSWORD: $'
    SEC1_DONE_MSG DB 'YOUR ACCOUNT WAS CREATED SUCCSESSFULLY. $'

    ;DISPLAY  ACCOUNT INFO

    SEC2_PRINT_ACC_NAME DB 'ACCOUNT NAME: $'
    SEC2_PRINT_ACC_PASS DB 'PASSWORD YOUR ACCOUNT: $'
    SEC_2_PRINT_NO_ACC DB 'THERE IS NO ACCOUNT $'
    SEC_2_PRINT_REMAINING_BALANCE DB 'YOUR REMAINING BALANCE: $'
    SEC2_PRINT_NO_MONEY DB 'YOUR ACCOUNT IS EMPTY $' 


    ;MONEY SECTION 
    SEC3_ONE DB 'TOMAN 1000 $'
    SEC3_TWO DB 'TOMAN 5000 $'
    SEC3_THREE DB 'TOMAN 10000 $'
    SEC3_FOUR DB 'TOMAN 50000 $'
    SEC3_SELECT_MONEY DB 'WHICH ONE DO YOU WANT $'
    SEC3_BALANCE_OVERFLOW DB 'THE AMOUNT OF MONEY YOU WANT HAS PASS ACCOUNT BALANCE $'

    ;CHANGE INFO
    SEC4_CHANGE_NAME DB 'YOUR NEW ACCOUNT NAME$'
    SEC4_CHANGE_PASS DB 'YOUR NEW PASSWORD $'
    SEC4_DONE_MSG DB 'YOUR ACCOUNT INFO HAS CHANGE SUCCSESSFULLY $'


    ;PIN 
    ENTER_PASS_MSG DB 'ENTER YOUR PASSWORD $'
    NO_ACC_MSG DB 'ACCOUNT DOES NOT EXIST $'

.CODE



