; Bank the 8086 Edition
; authors: Parsa KamaliPour 97149081, Hosein Ahmadi 97149003

.MODEL SMALL

.DATA

    INTRO_MSG DB 'Bank The 8086 Edition$'

    CREATE_MSG DB 'CREATE ACCOUNT$'

    DEPO_MSG DB 'DEPOSIT MONEY$'

    WITHDRAW_MSG DB 'WITHDRAW MONEY$'

    ACC_INFO_MSG DB 'ACCOUNT INFORMATION$'

    CHANGE_ACC_INFO_MSG DB 'CHANGE YOUR ACCOUNT INFORMATION$'

    QUESTION_MSG DB 'Choose your next option: $'

    INPUT DB ?

    ACC_NAME DB 50 DUP('$')

    ACC_PASSWORD DB 50 DUP('$')

    PASSWORD_SIZE DW 0

    ACC_BALANCE DW 0

    ; CREATE ACCOUNT SECTION

    SEC1_ENTER_MSG DB 'ENTER YOUR NAME: $'
    SEC1_PASS_MSG DB 'ENTER YOUR PASSWORD: $'
    SEC1_DONE_MSG DB 'YOUR ACCOUNT WAS CREATED SUCCSESSFULLY. $'

    